---
displayName: Bash
description: Stack with environment ready to develop bash scripts.
tags: ["Community", "Bash", "Shell"]
icon: /images/che.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/bash/tree/devfilev2
