---
displayName: Node.js React Web Application
description: Stack for developing Node.js React Web Application
tags: ["Community", "Node.js", "React", "Redux", "RealWorld"]
icon: /images/nodejs.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/nodejs-react-redux/tree/devfilev2
