---
displayName: "PHP Symfony"
description: PHP Stack with Symfony Demo Application https://symfony.com/
tags: ["Community", "PHP", "Apache", "MySQL", "Symfony", "Debian", "Centos"]
icon: /images/php.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/php-symfony/tree/devfilev2
