---
displayName: Java Spring Boot
description: Java stack with OpenJDK 11 and Spring Boot Petclinic demo application
tags: ["Community", "Java", "OpenJDK", "Maven", "Spring Boot"]
icon: /images/springboot.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/java-spring-petclinic/tree/devfilev2
