---
displayName: Python Django
description: Python Stack with Python 3.8 and Django application
tags: ["Community", "Centos", "Python", "pip"]
icon: /images/python.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/django-realworld-example-app/tree/devfile2
