---
displayName: Node.js Express Web Application
description: Stack with Node.js 10
tags: ["Community", "Node.js", "Express", "ubi8"]
icon: /images/nodejs.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/web-nodejs-sample/tree/devfilev2
