---
displayName: Apache Camel based on Spring Boot
description: Stack with environment ready to develop Integration projects with Apache Camel based on Spring Boot.
tags: ["Community", "Java", "OpenJDK", "Maven", "Debian", "Apache Camel", "Red Hat Fuse", "Spring Boot"]
icon: /images/camelk.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/fuse-rest-http-booster/tree/devfilev2
