---
displayName: Remote Browser
description: Stack with tooling ready to develop Integration projects with Remote Browser
tags: ["Community", "Remote Browser", "Red Hat Fuse", "Integration"]
icon: /images/icon_kasm.png
