---
displayName: Rust
description: Rust Stack with Rust 1.57
tags: ["Community", "Rust"]
icon: /images/rust.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/helloworld-rust/tree/devfilev2
