---
displayName: Node.js Angular Web Application
description: Stack for developing Node.js Angular Web Application
tags: ["Community", "Node.js", "Angular", "Alpine"]
icon: /images/angular.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/nodejs-angular/tree/devfilev2
