---
displayName: C/C++
description: Stack with C/C++ and Clang 8
tags: ["Community", "C/C++", "Clang", "g++", "GDB"]
icon: /images/cpp.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/cpp-hello-world/tree/devfilev2
