---
displayName: Scala
description: Scala Stack with OpenJDK 11 and sbt 1.x
tags: ["Community", "Scala", "OpenJDK", "sbt", "Debian"]
icon: /images/scala.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/scala-sbt/tree/devfilev2
