---
displayName: Apache Camel K
description: Stack with tooling ready to develop Integration projects with Apache Camel K
tags: ["Community", "Apache Camel K", "Red Hat Fuse", "Integration"]
icon: /images/camelk.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/apache-camel-k/tree/devfilev2
