---
displayName: Node.js MongoDB Web Application
description: Stack with NodeJS 10 and MongoDB 3.4
tags: ["Community", "Node.js", "Express", "MongoDB", "RealWorld", "ubi8", "Centos"]
icon: /images/nodejs.svg
links:
  v2: https://code.sdsdev.co.kr/cloud-ide-samples/nodejs-mongodb-sample/tree/devfilev2
